name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      run: |
        echo "The GitHub Action Secret will be masked: "
        echo ${{ secrets.Email_Password}} 
 
        
